replicaCount: 2

image:
  repository: docker.io/virtru/gateway
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 25

ingress:
  enabled: false

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 500Mi
  # requests:
  #   cpu: 500m
  #   memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Gateway Modes to enable, 
# each enabled mode will create a separate 
# deployment, service, and configmap

gatewayModes:
  outboundEncrypt:
    enabled: true
    name: oe-9001
    port: 9001
  outboundDecrypt:
    enabled: false
    name: od-9002
    port: 9002
  inboundEncrypt:
    enabled: false
    name: ie-9003
    port: 9003
  inboundDecrypt:
    enabled: false
    name: id-9004
    port: 9004
  outboundDlp:
    enabled: false
    name: dlp-out-9005
    port: 9005


# Environment Variables:
# For descriptions of all variables, see the README.md file

gatewayAccountsUrl: https://api.virtru.com/accounts
gatewayAcmUrl: https://api.virtru.com/acm
gatewayRemoteContentBaseUrl: https://secure.virtru.com/start

standardConfig:
  gatewayHostname: gw.example.com
  primaryMailingDomain: exmample.com
  amplitudeToken: <your-amplitude-token>
  gatewayApiTokenName: <your-api-token>
  gatewayApiSecret: <your-api-secret>
  gatewayTransportMaps: "*=>[smtp-relay.gmail.com]:587"
  # See README.md for Google or Microsoft relaying IPs,
  # default is open and to lock down firewall on the VPC
  inboundRelayAddresses: 0.0.0.0/0

additionalConfig:
  dkimSigning:
    enabled: false
    dkimDomains: gw._domainkey.example.com
  maxQueueLifetime: 5m
  maxBackoffTime: 45s
  minBackoffTime: 30s
  queueRunDelay: 30s
  smtpdUseTls: "1"
  smtpdSecurityLevel: opportunistic
  smtpdTlsComplianceUpstream:
    enabled: false
    compliance: MEDIUM
  smtpUseTls: "1"
  smtpSecurityLevel: opportunistic
  smtpTlsComplianceDownstream:
    enabled: false
    compliance: MEDIUM
  saslAuth:
    smtpDownstream:
      enabled: true
      securityOptions: noanonymous
      accounts: smtp-relay.gmail.com=>service-account@example.com=>password
    smtpdUpstream:
      enabled: false
      mechanisms: PLAIN
      accounts: smtp-relay.gmail.com=>service-account@example.com=>password
  headers:
    xHeaderAuthEnabled: false
    xHeaderAuthSecret: "123456789"
  cks:
    keyProvider: CKS
    sessionKeyExpiry: "360"
  dlpRuleCache: "30"
  tlsPolicyMaps:
    enabled: false
    policyMaps: example.com=>none,example.net=>maybe
  replaceFromEnabled: "1"
  decryptPfpFiles: "1"
  decryptThenEncrypt: "0"
  proxyProtocol: "0"
  verboseLogging: "0"