---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cse.fullname" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
data:
  ACCOUNTS_URL: {{ .Values.appConfig.accountsUrl }}
  ACM_URL: {{ .Values.appConfig.acmUrl }}
  JWKS_AUTHN_ISSUERS: {{ .Values.appConfig.jwksAuthnIssuers }}
  JWKS_AUTHZ_ISSUERS: {{ .Values.appConfig.jwksAuthzIssuers }}
  JWT_AUD: {{ .Values.appConfig.jwtAud }}
  JWT_KACLS_URL: {{ .Values.appConfig.jwtKaclsUrl }}
  PROCESS_NUMBER_OVERRIDE: "{{ .Values.appConfig.processNumberOverride }}"
  USE_SSL: "{{ .Values.appConfig.useSsl }}"
  USE_CKS: "{{ .Values.appConfig.useCks }}"
  {{- if eq .Values.appConfig.useCks true }}
  CKS_URL: "{{ .Values.appConfig.cksUrl }}"
  {{- end }}
