apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cse.fullname" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
type: Opaque
data:
  cse-hmac-token-id: {{ .Values.appSecrets.hmac.tokenId | b64enc | quote }}
  cse-hmac-token-secret: {{ .Values.appSecrets.hmac.tokenSecret | b64enc | quote }}
  cse-secret-key: {{ .Values.appSecrets.secretKey | b64enc | quote }}
  {{- if eq .Values.appConfig.useSsl "true" }}
  server.cert: {{ .Values.appSecrets.ssl.certificate | quote }}
  server.key: {{ .Values.appSecrets.ssl.privateKey | quote }}
  {{- end }}
