apiVersion: v1
kind: Service
metadata:
  name: {{ include "cse.fullname" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "cse.selectorLabels" . | nindent 4 }}
