# Default values for opentdf.
attributes:
  rootPath: /attributes
  publicName: "Attribute Authority"
  logLevel: CRITICAL
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_attribute_manager
    database: tdf_database
    schema: tdf_attribute
  oidc:
    clientId: tdf-attributes
    clientSecret: myclientsecret
    realm: tdf
#    trailing / is required
    serverUrl: http://opentdf-keycloak/auth/
    configurationUrl: http://opentdf-keycloak/auth/realms/tdf/.well-known/openid-configuration
    authorizationUrl: https://mgmt-green.virtru.com/keycloak/auth/realms/tdf/protocol/openid-connect/auth
    tokenUrl: https://mgmt-green.virtru.com/keycloak/auth/realms/tdf/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: mgmt-green.virtru.com
        paths:
          - path: /attributes(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2

claims:
  service:
    port: 4010
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_entitlement_reader
    database: tdf_database
    schema: tdf_entitlement
  ingress:
    enabled: true
    hosts:
      - host: mgmt-green.virtru.com
        paths:
          - path: /claims(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2

entitlement:
  rootPath: /entitlement
  publicName: "Entitlement"
  logLevel: CRITICAL
  corsOrigins: https://mgmt-green.virtru.com
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_entitlement_manager
    database: tdf_database
    schema: tdf_entitlement
  oidc:
    clientId: tdf-entitlement
    clientSecret: myclientsecret
    realm: tdf
#    trailing / is required
    serverUrl: http://opentdf-keycloak/auth/
    configurationUrl: http://opentdf-keycloak/auth/realms/tdf/.well-known/openid-configuration
    authorizationUrl: https://mgmt-green.virtru.com/keycloak/auth/realms/tdf/protocol/openid-connect/auth
    tokenUrl: https://mgmt-green.virtru.com/keycloak/auth/realms/tdf/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: mgmt-green.virtru.com
        paths:
          - path: /entitlement(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2

key-access:
  endpoints:
    easHost: http://opentdf-attributes:4020
    statsdHost: opentdf-statsd
    oidcPubkeyEndpoint: http://opentdf-keycloak
  ingress:
    enabled: true
    hosts:
      - host: mgmt-green.virtru.com
        paths:
          - path: /kas(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2