{{- if .Values.externalSecrets.virtruKeys.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.virtruKeys.name }}
type: Opaque
{{- with .Values.appSecrets.virtruKeys.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}