apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cks.fullname" . }}
  labels:
    {{- include "cks.labels" . | nindent 4 }}
data:
  AUTH_TOKEN_STORAGE_TYPE: "in-memory"
  LOG_RSYSLOG_ENABLED: "false"
  LOG_CONSOLE_ENABLED: "true"
  PORT: "{{ .Values.deployment.port }}"
  BOOT_CHECKER_IMPORT_PUBLIC_KEY_PATH: "/run/secrets/rsa001.pub"
  BOOT_CHECKER_IMPORT_PRIVATE_KEY_PATH: "/run/secrets/rsa001.pem"
  KEY_PROVIDER_PATH: {{ .Values.virtruKeys.mountPath }}
  KEY_PROVIDER_TYPE: "file"