{{- if .Values.externalSecrets.virtruAuth.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.virtruAuth.name }}
type: Opaque
data:
  AUTH_TOKEN_STORAGE_IN_MEMORY_TOKEN_JSON: {{ .Values.appSecrets.virtruAuth.data.authTokenJson | quote }}
{{- end }}