apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cks.fullname" . }}
  labels:
    {{- include "cks.labels" . | nindent 4 }}
type: Opaque
data:
  virtru-auth: {{ .Values.virtruAuth.authTokenJson | b64enc | quote }}
