apiVersion: v1
kind: Service
metadata:
  name: {{ include "cks.fullname" . }}
  labels:
    {{- include "cks.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "cks.selectorLabels" . | nindent 4 }}
