apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  arguments:
    parameters:
  templates:
  - name: main
    steps:
      - - name: workflow-links
          arguments:
            parameters:
              - name: buildImage
                value: '{{workflow.parameters.buildImage}}'
          templateRef:
            name: cwft-ci
            template: workflow-links
            clusterScope: true    

      - - name: checkout
          arguments:
            parameters:
            - name: appRepoDir
              value: '{{workflow.parameters.appRepoDir}}'
            - name: appRepoUrl
              value: '{{workflow.parameters.appRepoUrl}}'
            - name: branch
              value: '{{workflow.parameters.branch}}'
            - name: buildImage
              value: '{{workflow.parameters.buildImage}}'
          templateRef:
            name: cwft-git
            template: git-checkout-with-gitops
            clusterScope: true

      - - name: get-chart-version
          arguments:
            artifacts:
              - name: repo-source
                from: '{{steps.checkout.outputs.artifacts.repo-source}}'
            parameters:
              - name: gitRepoName
                value: '{{workflow.parameters.appRepoDir}}'
              - name: buildImage
                value: '{{workflow.parameters.buildImage}}'
              - name: chartDirectory
                value: 'cks/'
          templateRef:
            name: cwft-helm
            template: helm-publish-chart
            clusterScope: true

      - - name: publish-helm-chart
          arguments:
            artifacts:
              - name: repo-source
                from: '{{steps.checkout.outputs.artifacts.repo-source}}'
            parameters:
              - name: buildImage
                value: '{{workflow.parameters.buildImage}}'
              - name: appRepoDir
                value: '{{workflow.parameters.appRepoDir}}'
              - name: chartPath
                value: 'cks/'
              - name: chartVersion
                value: '{{steps.get-chart-version.outputs.result}}'
          templateRef:
            name: cwft-helm
            template: helm-publish-chart
            clusterScope: true
