apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: github-action-argo-submit-
spec:
  podGC:
    strategy: OnWorkflowCompletion
  arguments:
#! global to the workflow
    parameters:
    - name: buildImage
      value: "{{workflow.parameters.buildImage}}"
    - name: gitRepoName
      value: "{{workflow.parameters.gitRepoName}}"
    - name: charts
      value: |
        [
          { "directory": "cse" },
          { "directory": "cks" },
        ]

  entrypoint: virtru-charts-pipeline
  serviceAccountName: argo-events-sa
  templates:
    - name: virtru-charts-pipeline
      steps:
      - - name: git-checkout-with-gitops
          templateRef:
            name: cwft-git
            template: git-checkout-with-gitops
            clusterScope: true 
          arguments:
            parameters:
            - name: gitRepoName
              value: "{{workflow.parameters.gitRepoName}}"
            - name: gitRepoUrl
              value: "https://github.com/virtru-corp/virtru-charts.git"
            - name: defaultBranch
              value: "main"
            - name: credentialSecretName
              value: "virtru-cloudnative-secrets"

      - - name: get-chart-version
          templateRef:
            name: cwft-helm
            template: get-chart-version
            clusterScope: true 
          arguments:
            artifacts:
            - name: repo-source
              from: "{{steps.git-checkout-with-gitops.outputs.artifacts.repo-source}}"
            parameters:
            - name: gitRepoName
              value: "{{workflow.parameters.gitRepoName}}"
            - name: buildImage
              value: "{{workflow.parameters.buildImage}}"
            - name: chartDirectory
              value: "{{item.directory}}"
          withParam: "{{inputs.parameters.charts}}"

      - - name: get-app-version
          templateRef:
            name: cwft-helm
            template: get-app-version
            clusterScope: true 
          arguments:
            artifacts:
            - name: repo-source
              from: "{{steps.git-checkout-with-gitops.outputs.artifacts.repo-source}}"
            parameters:
            - name: gitRepoName
              value: "{{workflow.parameters.gitRepoName}}"
            - name: buildImage
              value: "{{workflow.parameters.buildImage}}"
            - name: chartDirectory
              value: "{{item.directory}}"
          withParam: "{{inputs.parameters.charts}}"

      - - name: create-map
          outputs:
            parameters:
            - name: chart-info-map
              value: "{{inputs.parameters.charts[item]}}, \"chartVersion\":{{steps.get-chart-version.outputs.result[item]}}, \"appVersion\":{{steps.get-app-version.outputs.result[item]}}"
          withSequence:
            start: 0
            end: 1

      - - name: strip-chart-version
          templateRef:
            name: cwft-helm
            template: strip-chart-version
            clusterScope: true 
          arguments:
            parameters:
            - name: buildImage
              value: "{{workflow.parameters.buildImage}}"
            - name: chartVersion
              value: "{{item.chartVersion}}"
          withParam: "{{steps.create-map.outputs.parameters.chart-info-map}}"

      - - name: helm-set-chart-versions
          templateRef:
            name: cwft-helm
            template: helm-set-chart-versions
            clusterScope: true 
          arguments:
            artifacts:
            - name: repo-source
              from: "{{steps.git-checkout-with-gitops.outputs.artifacts.repo-source}}"
            parameters: 
            - name: buildImage
              value: "{{workflow.parameters.buildImage}}"
            - name: gitRepoName
              value: "{{workflow.parameters.gitRepoName}}"
            - name: chartDirectory
              value: "{{item.directory}}"
            - name: chartVersion
              value: "{{item.chartVersion}}"
            - name: defaultBranch
              value: main
            - name: dockerTag
              value: "{{item.appVersion}}"
            - name: githubOrg
              value: virtru-corp
            - name: githubSecretName
              value: virtru-cloudnative-secrets
          withParam: "{{steps.create-map.outputs.parameters.chart-info-map}}"

      - - name: helm-push
          templateRef:
            name: cwft-helm
            template: helm-push-it
            clusterScope: true 
          arguments:
            artifacts:
            - name: repo-source
              from: "{{steps.helm-set-chart-versions.outputs.artifacts.repo-source}}"
            parameters: 
            - name: buildImage
              value: "{{workflow.parameters.buildImage}}"
            - name: chartDirectory
              value: "{{item.directory}}"
            - name: gitRepoName
              value: "{{workflow.parameters.gitRepoName}}"
            - name: chartVersion
              value: "{{item.chartVersion}}"
          withParam: "{{steps.create-map.outputs.parameters.chart-info-map}}"
