{{- if eq .Values.additionalConfig.dkimSigning.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dkim-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  {{ .Values.additionalConfig.dkimSigning.selector }}._domainkey.{{ .Values.standardConfig.primaryMailingDomain }}-public.pem: {{ .Values.appSecrets.dkimSigning.publicKey | b64enc | quote }}
  {{ .Values.additionalConfig.dkimSigning.selector }}._domainkey.{{ .Values.standardConfig.primaryMailingDomain }}.pem: {{ .Values.appSecrets.dkimSigning.privateKey | b64enc | quote }}
{{- end }}