name: publish-chart

defaults:
  run:
    shell: bash

on: workflow_dispatch

jobs:
  argo_submit:
    runs-on: ubuntu-latest
    name: Argo submit workflow
    
    steps:
      - name: Get application name
        id: app-name
        run: echo "::set-output name=app::$(echo '${{ github.repository }}' | cut -d '/' -f 2)"

      - name: Checkout Virtru GitHub Actions repo
        uses: actions/checkout@v2
        with:
          repository: virtru-corp/github-actions
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./github-actions

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.MARS_AWS_ROLE_TO_ASSUME }}
          role-external-id: GitHubAction
          role-duration-seconds: 1200
          role-session-name: ${{ steps.app-name.outputs.app }}-action

      - name: Submit Argo workflow
        uses: ./github-actions/submit-a-custom-workflow
        